[main]
font=Cascadia Mono:size=11
pad=12x12 center
selection-target=clipboard

[cursor]
style=beam
blink=yes

[mouse]
hide-when-typing=yes

[colors]
background=${BASE}
foreground=${TEXT}

selection-foreground=${BASE}
selection-background=${ACCENT}

# ANSI colors
regular0=${COLOR0}
bright0=${COLOR8}
regular1=${COLOR1}
bright1=${COLOR9}
regular2=${COLOR2}
bright2=${COLOR10}
regular3=${COLOR3}
bright3=${COLOR11}
regular4=${COLOR4}
bright4=${COLOR12}
regular5=${COLOR5}
bright5=${COLOR13}
regular6=${COLOR6}
bright6=${COLOR14}
regular7=${COLOR7}
bright7=${COLOR15}
